export const CSUFCoords = {
    latitude: 33.88251681175372,
    longitude: -117.88512475905357,
    latitudeDelta: 0.009,
    longitudeDelta: 0.009,    
}

export const BUILDING_NAMES = [
    'AF-Anderson Field',
    'B-Bookstore/Titan Shops',
    'BA-Becker Amphitheater',
    'BGC-Greenhouse Complex',
    'CC-Childrens Center',
    'CJ-Carls Jr.',
    'CP-College Park',
    'CPAC-Clayes Performing Arts Center',
    'CY-Corporation Yard',
    'CS-Computer Science',
    'DBH-Dan Black Hall',
    'E-Engineering',
    'EC-Education-Classroom',
    'EPS-Eastside Parking Structure',
    'G-Golleher Alumni House',
    'GF-Goodwin Field',
    'H-Humanities-Social Sciences',
    'KHS-Kinesiology & Health Science',
    'LH-Langsdorf Hall',
    'MH-McCarthy Hall',
    'P-Parking & Transportation Office',
    'RH-Residence Halls',
    'PL-Pollak Library',
    'R-Receiving',
    'RGC-Ruby Gerontology Center',
    'SHCC-Student Health & Counseling Center',
    'SGMH-Mihaylo Hall',
    'SH-Student Housing',
    'SRC-Student Rec Center',
    'TG-Titan Gymnasium',
    'TH-Titan House',
    'TS-Titan Stadium',
    'TSU-Titan Student Union',
    'UH-University Hall',
    'UP-University Police',
    'VA-Visual Arts',
    'NPS-Nutwood Parking Structure',
    'SCPS-State College Parking Structure'    
]